server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          # Optional: Enable debug mode for troubleshooting
          debug: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env
  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret-key: ${SECRET_KEY}
    expiration-time: ${EXPIRATION_TIME}

logging:
  level:
    root: INFO
    com.test.commerce: DEBUG

amazon:
  s3uploadbucket: ${AWS_BUCKET}
  region: ${AWS_REGION}
